### ISSUE TITLE
rom doesn't boot

### ISSUE THREAD

**Issue by kyoto44** [xiaomi-classic-dev/android_device_xiaomi_libra#1]
i built rom using your sources but i didn't even boot

**Comment by GuaiYiHu** [comment]
My code can't work better on my own device.

**Comment by kyoto44** [comment]
Can you share your repopicks or something you did to get it boot?
ROM bootloops while using all your repos (android_device_xiaomi_libra, android_device_xiaomi_msm8994-common, vendor, android_kernel_xiaomi_leo)

**Comment by adi8900** [comment]
check logs and you should see the problem why didn't boot for you....
